Feature/4 read post list
wanted-team-p/sns pull request #6
Opened 2023-10-29 20:43 UTC by unknownKade

## #4 게시물 목록을 조회한다

#### 개발 내용
- 게시물 목록 조회 및 검색 구현

예시 쿼리:
[GET] /post?pageCount=3&page=0&searchBy=title,content&search=법률&orderBy=updatedAt&hashtag=해시태그1

예시 결과:
``` json
[
    {
        "id": 5,
        "title": "제목2",
        "type": "twitter",
        "content": "대통령의 선거에 관한 사항은 법률로 ",
        "viewCount": 20,
        "likeCount": 10,
        "shareCount": 20,
        "hashtagList": [
            "해시태그1"
        ],
        "updatedAt": "2023-10-31T05:29:44.968809",
        "createdAt": "2023-10-31T05:29:44.968809"
    }
]
```

#### 변경사항
- 쿼리 파라미터를 스네이크 케이스 -> 캐멀 케이스로 구현
- 게시물 테스트 데이터 생성

2023-11-02 21:03 UTC, hanull requested changes
수고하셨어요. 몇몇 코멘트 남겼는데 확인해주세요~!

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/controller/PostController.java
> +@RequestMapping("/post")
단수형을 사용하신 이유가 있으신가요?
아래와 같이 모든 게시글을 불러오는 경우 의미가 조금 어색한 것 같네요.

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/controller/PostController.java
> +
불필요한 개행이라고 생각해요.

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Hashtag.java
> +    private long seq;
id를 원시타입으로 사용하면 발생하는 문제점이 있을 것 같아요~!

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        return result.stream().map(PostResponse::new).collect(Collectors.toList());
👀

2023-11-02 21:03 UTC, hanull commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +public class PostReadTest {
어떤 테스트를 하신 건지 클래스명을 의미있게 작성해주면 좋을 것 같아요. + 패키지명
그리고 추가적으로 service에 대한 테스트를 작성해보면 좋을 것 같아요. 페이지당 10건씩 조회 되는지,  추천 수 등등으로 잘 조회 되는지를 확인해보면 좋을 것 같아요.

2023-11-02 21:03 UTC, hanull commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +    @DisplayName("게시글 목록 조회 테스트")
인수 테스트는 클라이언트가 요구하는 응답이 올바른지 검증하는 테스트라고 생각해요. 그래서 어떤 응답을 검증하고자 하는지 정확하게 작성하면 좋을 것 같아요.

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private int shareCount;
올바르지 않은 값이 들어갈 수 있겠네요.

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/dto/PostRequest.java
> +            pageCount = 10;
사용자가 요청한 값이 아니라 임의의 값을 넣어주네요?! 사용자가 잘못된 요청하면 예외를 발생하는게 맞지 않을까요?

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private LocalDateTime createdAt;
현재는 data.sql로 임의의 값을 넣어줘서 날짜가 잘 들어가지만, 실제로 게시글을 등록할 때는 날짜가 안들어 갈 것 같아요

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Post.java
> +    List<HashtagMapping> hashtagMappingList;
변수명에 자료형이 들어가는 것이 좋은 네이밍일까요?!

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        Fetch<Post, HashtagMapping> hashtagMapping = post.fetch("hashtagMappingList");
fetch() 메서드의 attribute name이 달라진다면..?!

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +    public List<PostResponse> findAllPostBy(PostRequest postRequest) {
PostRequest 를  controller -> service -> repository 모든 계층에서 사용하고 있네요. 만약 요구사항이 수정되서 request 데이터가 변경된다면 많은 부분 변경이 발생하겠네요.

2023-11-02 21:03 UTC, hanull commented on src/test/java/com/wanted/sns/repository/PostRepositoryTest.java
> +        SoftAssertions.assertSoftly(softAssertions -> {
SoftAssertions 새로운 방법 배워갑니다 👍

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/SnsType.java
> +        return null;
type을 찾지 못한 경우, null 보다는 예외를 던져주는게 좋을 것 같아요.

2023-11-02 21:03 UTC, hanull commented on src/main/java/com/wanted/sns/domain/SnsType.java
> +        for (SnsType snsType : SnsType.values()) {
stream을 사용해볼까요?

2023-11-03 01:30 UTC, unknownKade commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        Fetch<Post, HashtagMapping> hashtagMapping = post.fetch("hashtagMappingList");
코멘트가 잘 이해가 안되는데, 엔티티에 지정한 이름이라 변수가 달라진다면 fetchJoin이 안되겠죠!?

2023-11-03 01:48 UTC, unknownKade commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +public class PostReadTest {
목록만 있어서 애매한 클래스명으로 보일 수 있겠군요. 해당 테스트 클래스에는 조회 관련으로 다 들어가서 Read으로 지정했습니다.
단위 테스트와 통합테스트 둘 다 있고 서비스와 컨트롤러 사이 로직이 또 있지 않는 경우 서비스 테스트를 또 진행하는 것은 불필요하다고 생각합니다. 서비스와 컨트롤러 사이에서 새로운 로직이 없어서 사실상 같은 테스트가 두 번인데 그 효용과 비용을 따져서 작성해야하는 테스트와 아닌 것도 구분해야한다고 봐요.
패키지명은 한울님이 통합테스트를 기능으로 빼놓은 것 같아 기능으로 뺐는데, 아니라면 어떤 패키지 구조 규칙을 생각하고 계셨나요?

2023-11-03 02:50 UTC, unknownKade commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +    @DisplayName("게시글 목록 조회 테스트")
말씀하신 바를 Nested의 이름에 어떻게 적용해야할지 예시를 부탁드립니다.

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +    public List<PostResponse> findAllPostBy(PostRequest postRequest) {
그렇겠네요, 다른 대안은 어떤 것이 있을까요?

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/dto/PostRequest.java
> +            pageCount = 10;
값이 없는 경우 디폴트 값입니다. 혹시 한울님이 실행하셨을 때 요청값을 오버라이딩하나요?

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/SnsType.java
> +        for (SnsType snsType : SnsType.values()) {
왜 stream.forEach를 사용하지 않았는지를 묻는 것으로 이해되는데, stream 하는 전체를 다 loop 하지 않는 경우에 대해 stream을 사용하는 것은 비효율적이고 GB에 불필요한 과부하가 걸리는 것으로 봅니다. 이렇게 특정 값을 찾는 로직에 대해서는 for loop이 맞다고 생각합니다. 아래 링크도 참고 부탁드립니다.

stream의 작동 원리 : https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StreamOps
stream vs for loop : https://tecoble.techcourse.co.kr/post/2020-05-14-foreach-vs-forloop/

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private int shareCount;
코드리뷰에서 생각하시는 문제점이 무엇인지, 해결방안이 어떤것이 있는지 구체적으로 제시해주기시길 바랍니다.
효과적인 코드리뷰 작성에 대해서는 아래 링크 참고부탁드립니다.

https://tech.kakao.com/2022/03/17/2022-newkrew-onboarding-codereview/

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private LocalDateTime createdAt;
저희 게시글 등록이 없고 조회만 하는 서비스입니다.

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/Post.java
> +    List<HashtagMapping> hashtagMappingList;
불가피하게 자료형과 같아졌지만 자료형이 들어간 것이 아니라 목록이란 명사입니다.
다른 네이밍을 생각하시는 경우 코드리뷰에서는 어떤 네이밍으로 바꿔야한다고 생각하는지 제안 부탁드립니다.

2023-11-03 02:50 UTC, unknownKade commented on src/main/java/com/wanted/sns/controller/PostController.java
> +@RequestMapping("/post")
기능에 대해서는 복수형을 지양하고 있어요.
목록 불러올 때는 이상 할 수 있겠네요. 고민해 봐야할 부분 같네요.

2023-11-03 03:16 UTC, hanull commented on src/main/java/com/wanted/sns/controller/PostController.java
> +@RequestMapping("/post")
복수형을 사용하는 것을 권장하고 있습니다!
https://restfulapi.net/resource-naming/
https://stackoverflow.com/questions/6845772/should-i-use-singular-or-plural-name-convention-for-rest-resources

2023-11-03 03:16 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Hashtag.java
> +    private long seq;
어떤 문제가 있을지 작성해주시면 좋을 것 같아요~!

2023-11-03 03:18 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        return result.stream().map(PostResponse::new).collect(Collectors.toList());
한 줄에 하나의 점만 사용한다!

2023-11-03 03:24 UTC, hanull commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +public class PostReadTest {
저는 테스트의 목적이 다르기 때문에 필요하다고 생각해요. 현재 작성해주신 테스트는 인수 테스트라고 생각하는데 이 경우에는 요구사항에 대한 응답이 올바른지, 즉 상태코드 또는 응답 데이터를 확인하는 과정이라고 생각해요. 그리고 통합 테스트는 개발자 관점에서 기능이 올바르게 동작하는지를 테스트한다고 생각합니다.

2023-11-03 03:26 UTC, hanull commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +    @DisplayName("게시글 목록 조회 테스트")
ex) 게시글 목록 조회에 성공하면, 상태코드 200을 반환한다.

2023-11-03 03:29 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private int shareCount;
좋은 글 감사합니다.
제가 확실한 방법을 제시하지 않은 이유는 학습하는 입장이기 때문에 스스로 고민해보는 것이 좋을 것 같다고 판단했기 때문이에요. 

위의 경우에서 발생할 수 있는 문제점은 음수값이 들어갈 수 있겠네요

2023-11-03 03:31 UTC, hanull commented on src/main/java/com/wanted/sns/dto/PostRequest.java
> +            pageCount = 10;
아하 이 부분은 제가 이해를 잘 못한 것  같아요. 
추가로 페이징을 고려해보면 좋을 것 같네요

2023-11-03 03:37 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        Fetch<Post, HashtagMapping> hashtagMapping = post.fetch("hashtagMappingList");
post.fetch("hashtagMappingList") 에서 속성명이 달라질 수 있다는 얘기였습니다. 
의미있는 상수로 빼서 관리하면 편할 것 같아요

2023-11-03 03:38 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Post.java
> +    List<HashtagMapping> hashtagMappingList;
https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/
hashtagMappings 또는 hashtags 라고 하면 좋을 것 같아요.

2023-11-03 03:42 UTC, hanull commented on src/main/java/com/wanted/sns/domain/SnsType.java
> +        for (SnsType snsType : SnsType.values()) {
stream.forEach 를 사용한다면 그럴 수 있겠네요.
제가 생각한 방법은 filter 입니다.

```java
return Arrays.stream(values())
                .filter(snsType -> snsType.value.equalsIgnoreCase(value))
                .findFirst()
                .orElseThrow(IllegalArgumentException::new);
```

2023-11-03 03:48 UTC, unknownKade commented on src/test/java/com/wanted/sns/post/PostReadTest.java
> +    @DisplayName("게시글 목록 조회 테스트")
그건 이 클래스에 nested 된 각 테스트에 들어갈 이름으로 봅니다.

2023-11-03 04:37 UTC, hanull commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +    public List<PostResponse> findAllPostBy(PostRequest postRequest) {
중간 객체를 두는 방법이 있을 것 같아요! 새로운 객체를 생성하던가, Pageable 인터페이스를 구현한 PageRequest 객체가 있더라구요 이걸 사용해도 될 것 같다는 생각이 들었어요.

2023-11-03 04:45 UTC, unknownKade commented on src/main/java/com/wanted/sns/repository/PostCustomRepositoryImpl.java
> +        return result.stream().map(PostResponse::new).collect(Collectors.toList());
위의 코멘트와 충돌이 있네요. 저희 한 줄 당 한 점만 지킬 것인가요, 아니면 불필요한 개행은 하지 않을건가요?

2023-11-03 04:45 UTC, unknownKade commented on src/main/java/com/wanted/sns/dto/PostRequest.java
> +            pageCount = 10;
네 jpa의 페이징 인터페이스 말씀하시는것인가요?

2023-11-03 04:45 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/Hashtag.java
> +    private long seq;
한울님이 면접관인 면접 자리가 아닙니다. 제가 그거에 답하는게 아니라 코드리뷰에 이걸 얘기하고 싶었다면 한울님이 왜 long이 잘못 되었다고 생각하는지 코멘트에 달았어야했어요.
별 말 없이 넘어갔지만 이거에 대해서 저흰 이미 얘기도했고 전 이미 이렇게 만들었기 때문에 일단 이렇게 진행하기로 한 것도 저희가 같이 사전에 얘기했던 부분이고요.
이미 이런 무례에 대해 디스코드로도 주의를 줬는데 계속 이러시면 곤란합니다. 어떤 부분에서 저에게 훈교를 해도 된다고 느끼시는지 모르지만 이는 팀 규칙에도 어긋나고 계속 되면 운영과 함께 이 문제에 대한 얘기를 진행하겠습니다.

2023-11-03 04:45 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/Post.java
> +    private int shareCount;
스스로 고민할 수 있는 코멘트에 대해서는 해당 글에도 제시되어있으니 본인의 코멘트와 비교해보시면 좋을 것 같습니다.
저희는 sns피드 서비스입니다. 다른 코멘트에도 답 드렸다시피 조회만 있으므로 잘못 들어가는 경우가 없습니다. 조회한 api에서 음수를 줬다면 음수가 들어가야한다고 생각합니다.

2023-11-03 04:45 UTC, unknownKade commented on src/main/java/com/wanted/sns/domain/SnsType.java
> +        for (SnsType snsType : SnsType.values()) {
filter를 생각하셨군요. 하지만 결국 close가 늦어지고 불필욯나 과부하인건 차이 없습니다. 실제로 여러개 중 첫번째 것을 찾는 경우가 아니라 특정 값을 찾는다면 의도 전달을 위해 쓰겠지만 성능면에서는 for 루프가 빠릅니다.
그외에도 근소한 성능차에 대해 함수형 표현을 쓰는 것은 개발자 개인 성향인 부분이라 리뷰 하실 부분이 아닙니다.

2023-11-03 04:57 UTC, hanull commented on src/main/java/com/wanted/sns/domain/Hashtag.java
> +    private long seq;
먼저 그렇게 느끼셨다면 우
죄송합니다. 그런데 저의 의도는 훈교? 가 아니고 적어보면서 한 번 더 생각해볼 수 있다고 생각했기 때문이에요. 그동안 이렇게 공부하는게 도움이 됐다고 생각했거든요. 
제 생각인데 남들도 이렇게 생각하겠다고 착각했네요. 주의하겠습니다

2023-11-03 13:21 UTC, hanull approved these changes

2023-11-06 08:20 UTC, merged